vich_uploader:
    db_driver: orm

    mappings:
        event_images:
            uri_prefix: /images/event
            upload_destination: '%kernel.project_dir%/public/images/evnt'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
